all:
	gcc str_echo.c serv.c -g -Wall -o serv01 -lpthread -static
	gcc str_cli.c client.c -g -Wall -o cli01 -lpthread -static
serv:
	gcc str_echo.c serv.c -g -Wall -o serv01 -lpthread -static
cli:
	gcc str_cli.c client.c -g -Wall -o cli01 -lpthread -static
