all:
	gcc serv.c -g -Wall -o serv01 -lpthread -static
	gcc client.c -g -Wall -o cli01 -lpthread -static
serv:
	gcc serv.c -g -Wall -o serv01 -lpthread -static
cli:
	gcc client.c -g -Wall -o cli01 -lpthread -static
